# Generated by Django 5.0.3 on 2024-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSolicitud",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.CharField(max_length=255)),
                ("solicitud", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
